import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { resolve, dirname } from 'path';

const WAT_PATH = resolve(import.meta.dirname, '../lib/optimizer/wasm/kernels.wat');
const OUTPUT_TS = resolve(import.meta.dirname, '../lib/optimizer/wasm/kernels.wasm.generated.ts');
const OUTPUT_WASM = resolve(import.meta.dirname, '../public/kernels.wasm');

async function main() {
  const wabt = (await import('wabt')).default;
  const wabtApi = await wabt();

  const watSource = readFileSync(WAT_PATH, 'utf-8');
  const parsed = wabtApi.parseWat('kernels.wat', watSource);
  const binary = parsed.toBinary({ write_debug_names: false });
  const wasmBytes = Buffer.from(binary.buffer);

  writeFileSync(OUTPUT_WASM, wasmBytes);
  const base64 = wasmBytes.toString('base64');
  const ts = `// Auto-generated by scripts/build-wasm.mjs — do not edit
export const WASM_BASE64 = ${JSON.stringify(base64)};
export const WASM_BYTE_LENGTH = ${wasmBytes.length};
`;

  mkdirSync(dirname(OUTPUT_TS), { recursive: true });
  writeFileSync(OUTPUT_TS, ts, 'utf-8');
  console.log(`kernels.wasm generated (${wasmBytes.length} bytes)`);
}

main().catch((err) => { console.error(err); process.exit(1); });
