import * as esbuild from 'esbuild';
import { writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');

async function buildWorker() {
  const result = await esbuild.build({
    entryPoints: [join(root, 'lib/optimizer/worker/worker.ts')],
    bundle: true,
    format: 'iife',
    globalName: '__pw_worker',
    minify: true,
    write: false,
    target: 'es2017',
  });

  const code = result.outputFiles[0].text;

  const output = `// Auto-generated by scripts/build-worker.mjs — DO NOT EDIT
export const WORKER_SCRIPT: string = ${JSON.stringify(code)};
`;

  writeFileSync(join(root, 'lib/optimizer/worker/worker.generated.ts'), output);
  console.log(`worker.generated.ts written (${(code.length / 1024).toFixed(1)} KB)`);
}

buildWorker().catch((err) => {
  console.error('Worker build failed:', err);
  process.exit(1);
});
